### ISSUE TITLE
请问，计算最大缓存开销的代码怎么写？

### ISSUE THREAD

**Issue by zfx666666** [Zheng-MJ/SMFANet#10]

**Comment by Zheng-MJ** [comment]
感谢您的关注。

推理时的最大显存开销代码：
[    max_memory = torch.cuda.max_memory_allocated(torch.cuda.current_device()) / 1024 ** 2
](https://github.com/Zheng-MJ/SMFANet/blob/a05e0bb554bbbb80cd27d8fd2b78d4228c657170/plt/main_flops.py#L48)

希望您的研究顺利！如果其他问题，欢迎继续交流。

**Comment by zfx666666** [comment]
大佬，太感谢了！很荣幸能和您交流学术。
















在 2024-12-29 19:45:27，"zheng" ***@***.***> 写道：

感谢您的关注。

推理时的最大显存开销代码：
max_memory = torch.cuda.max_memory_allocated(torch.cuda.current_device()) / 1024 ** 2


希望您的研究顺利！如果其他问题，欢迎继续交流。
