### ISSUE TITLE
实验结果复现问题

### ISSUE THREAD

**Issue by linanfang115** [Zheng-MJ/SMFANet#6]
作者你好，我使用了你们在huggingface上提供的权重文件SMFANet_DIV2K_100w_x4SR.pth,但是在Set14和BSD100数据集上的指标和论文中的结果相差还是较多。
![image](https://github.com/user-attachments/assets/9ef637ee-c889-41b1-ac09-b2337ffcee8b)

**Comment by Zheng-MJ** [comment]
可能是pytorch的bicubic退化的影响，建议重新合成一下数据，测试集的Set14和BSD100的数据集采用matlab的bicubic退化

**Comment by linanfang115** [comment]
感谢回复，确实是数据集的问题，我下午换了matlab处理过的数据后跑的指标几乎一致。
祝好！

**Comment by zmmdeid** [comment]
> 感谢回复，确实是数据集的问题，我下午换了matlab处理过的数据后跑的指标几乎一致。 祝好！
你好，请问测试完有效果图吗，，我怎么没找到,,,,.....

**Comment by linanfang115** [comment]
> > 感谢回复，确实是数据集的问题，我下午换了matlab处理过的数据后跑的指标几乎一致。 祝好！
> > 你好，请问测试完有效果图吗，，我怎么没找到,,,,.....

这个需要在options/test中的yml文件中将 save_img 置为true，结果在 results 文件夹中

**Comment by zmmdeid** [comment]
> > > 感谢回复，确实是数据集的问题，我下午换了matlab处理过的数据后跑的指标几乎一致。 祝好！
> > > 你好，请问测试完有效果图吗，，我怎么没找到,,,,.....
> 
> 这个需要在options/test中的yml文件中将 save_img 置为true，结果在 results 文件夹中
谢谢回复~找到啦！
