### ISSUE TITLE
Training configurations

### ISSUE THREAD

**Issue by c-yn** [Zheng-MJ/SMFANet#9]
Great work!

I have a few questions regarding the training configurations:

1. Did you use a single 3090 GPU for all experiments? If so, how long did each experiment take?

2. You mentioned running 1000K iterations. Do you think this could introduce a potential fairness issue when compared with other methods?

3. When training models for x3/x4, did you use the pre-trained model from x2 as a starting point?

Thank you very much for taking the time to answer my questions.

**Comment by Zheng-MJ** [comment]
Thank you for your interest in our work.

1. All experiments for SMFANet were conducted using a single 3090 GPU. For the larger version, SMFANet+, adjustments to the batch size or the use of two GPUs might be necessary. The training time for SMFANet is approximately 3 days, while for SMFANet+ it is around 5 days.

2. We are committed to ensuring the fairness of our experimental comparisons. Training for 1,000,000 iterations allows the network to converge sufficiently, which is beneficial for performance enhancement. However, we find that the network approaches convergence around 500,000 iterations, so reducing the training duration can still yield comparable results.

3. For the models trained at x3 and x4 scales, we do **not** use the pre-trained model from x2 as a starting point.

Wishing you success in your research endeavors!

**Comment by Zheng-MJ** [comment]
Thank you for your interest in our work.

1. All experiments for SMFANet were conducted using a single 3090 GPU. For the larger version, SMFANet+, adjustments to the batch size or the use of two GPUs might be necessary. The training time for SMFANet is approximately 3 days, while for SMFANet+ it is around 5 days.

2. We are committed to ensuring the fairness of our experimental comparisons. Training for 1,000,000 iterations allows the network to converge sufficiently, which is beneficial for performance enhancement. However, we find that the network approaches convergence around 500,000 iterations, so reducing the training duration can still yield comparable results.

3. For the models trained at x3 and x4 scales, we do **not** use the pre-trained model from x2 as a starting point.

Wishing you success in your research endeavors!

**Comment by c-yn** [comment]
Thank you very much for your answers.
